providers = []
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1707782610'

[variables]
CI = 'true'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'

[phases.build]
dependsOn = ['install']
cmds = ['npm run build']
cacheDirectories = [
    '.next/cache',
    'node_modules/.cache',
]

[phases.install]
dependsOn = ['setup']
cmds = ['npm install']
cacheDirectories = ['/root/.npm']
paths = ['/app/node_modules/.bin']

[phases.setup]
nixPkgs = [
    'nodejs_18',
    'npm',
    'openssl',
]

[start]
cmd = 'npm run start'
